// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {torrent} from '../models';
import {context} from '../models';

export function AddTorrent(arg1:Array<number>):Promise<torrent.Torrent>;

export function RemoveTorrent(arg1:any):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
