// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTorrent(arg1) {
  return window['go']['torrent']['Client']['AddTorrent'](arg1);
}

export function GetTorrentStats(arg1) {
  return window['go']['torrent']['Client']['GetTorrentStats'](arg1);
}

export function RemoveTorrent(arg1) {
  return window['go']['torrent']['Client']['RemoveTorrent'](arg1);
}

export function Startup(arg1) {
  return window['go']['torrent']['Client']['Startup'](arg1);
}
