// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTorrent(arg1, arg2) {
    return window['go']['torrent']['Client']['AddTorrent'](arg1, arg2)
}

export function GetDefaultConfig() {
    return window['go']['torrent']['Client']['GetDefaultConfig']()
}

export function GetPeerMessageHistory(arg1, arg2, arg3) {
    return window['go']['torrent']['Client']['GetPeerMessageHistory'](arg1, arg2, arg3)
}

export function GetTorrentConfig(arg1) {
    return window['go']['torrent']['Client']['GetTorrentConfig'](arg1)
}

export function GetTorrentStats(arg1) {
    return window['go']['torrent']['Client']['GetTorrentStats'](arg1)
}

export function RemoveTorrent(arg1) {
    return window['go']['torrent']['Client']['RemoveTorrent'](arg1)
}

export function SelectDownloadDirectory() {
    return window['go']['torrent']['Client']['SelectDownloadDirectory']()
}

export function Startup(arg1) {
    return window['go']['torrent']['Client']['Startup'](arg1)
}

export function UpdateTorrentConfig(arg1, arg2) {
    return window['go']['torrent']['Client']['UpdateTorrentConfig'](arg1, arg2)
}
