// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import { torrent } from '../models'
import { config } from '../models'
import { context } from '../models'

export function AddTorrent(arg1: Array<number>): Promise<torrent.Torrent>

export function GetConfig(): Promise<config.Config>

export function GetTorrentStats(arg1: string): Promise<torrent.Stats>

export function RemoveTorrent(arg1: string): Promise<void>

export function SelectDownloadDirectory(): Promise<string>

export function Startup(arg1: context.Context): Promise<void>

export function UpdateConfig(arg1: config.Config): Promise<void>
